# Generated by Django 4.1 on 2022-08-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indoorGeolocation", "0005_alter_node_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAccount",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="indoorGeolocation.person",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=25)),
                ("id_in_org", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
            bases=("indoorGeolocation.person",),
        ),
    ]
