# Generated by Django 4.0.3 on 2022-07-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorGeolocation', '0002_alter_position_instant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='y',
            field=models.FloatField(),
        ),
    ]
