# Generated by Django 4.0.3 on 2022-08-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoorGeolocation', '0003_alter_position_x_alter_position_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='indoorGeolocation.device')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indoorGeolocation.node')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('indoorGeolocation.node',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indoorGeolocation.node')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
            bases=('indoorGeolocation.node',),
        ),
    ]
